packages:
  - "desktop-app"
  - "mobile-app"
  - "web-app"

allowBuilds:
  '@hurdlegroup/robotjs': set this to true or false
  electron: true
  esbuild: true
  omnicontrol-desktop: true
  omnicontrol-mobile: true
  omnicontrol-web: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies: '@hurdlegroup/robotjs'
